// Generated by CIRCT firtool-1.109.0
module op_FPOP_add_I32W_I32W_O32W(	// git/chisel-template/src/main/scala/hls_float/hls_float.scala:199:7
  output        i0_ready,	// git/chisel-template/src/main/scala/hls_float/hls_float.scala:200:14
  input         i0_valid,	// git/chisel-template/src/main/scala/hls_float/hls_float.scala:200:14
  input  [31:0] i0_data,	// git/chisel-template/src/main/scala/hls_float/hls_float.scala:200:14
  output        i1_ready,	// git/chisel-template/src/main/scala/hls_float/hls_float.scala:201:14
  input         i1_valid,	// git/chisel-template/src/main/scala/hls_float/hls_float.scala:201:14
  input  [31:0] i1_data,	// git/chisel-template/src/main/scala/hls_float/hls_float.scala:201:14
  input         o0_ready,	// git/chisel-template/src/main/scala/hls_float/hls_float.scala:202:14
  output        o0_valid,	// git/chisel-template/src/main/scala/hls_float/hls_float.scala:202:14
  output [31:0] o0_data,	// git/chisel-template/src/main/scala/hls_float/hls_float.scala:202:14
  input         clk,	// git/chisel-template/src/main/scala/hls_float/hls_float.scala:203:15
                reset	// git/chisel-template/src/main/scala/hls_float/hls_float.scala:204:17
);

  wire _vivado_fadd_comb_m_axis_result_tvalid;	// git/chisel-template/src/main/scala/hls_float/hls_float.scala:209:19
  wire i1_ready_0 = o0_ready & _vivado_fadd_comb_m_axis_result_tvalid;	// git/chisel-template/src/main/scala/hls_float/hls_float.scala:209:19, :214:24
  vivado_fadd_comb vivado_fadd_comb (	// git/chisel-template/src/main/scala/hls_float/hls_float.scala:209:19
    .s_axis_a_tvalid      (i0_valid),
    .s_axis_a_tdata       (i0_data),
    .s_axis_b_tvalid      (i1_valid),
    .s_axis_b_tdata       (i1_data),
    .m_axis_result_tvalid (_vivado_fadd_comb_m_axis_result_tvalid),
    .m_axis_result_tdata  (o0_data)
  );	// git/chisel-template/src/main/scala/hls_float/hls_float.scala:209:19
  assign i0_ready = i1_ready_0;	// git/chisel-template/src/main/scala/hls_float/hls_float.scala:199:7, :214:24
  assign i1_ready = i1_ready_0;	// git/chisel-template/src/main/scala/hls_float/hls_float.scala:199:7, :214:24
  assign o0_valid = _vivado_fadd_comb_m_axis_result_tvalid;	// git/chisel-template/src/main/scala/hls_float/hls_float.scala:199:7, :209:19
endmodule


