// Generated by CIRCT firtool-1.109.0

// Include register initializers in init blocks unless synthesis is set
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Standard header to adapt well known macros for register randomization.

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_
module op_FPOP_mul_I32W_I32W_O32W_HandshakeSingleDelay(	// git/chisel-template/src/main/scala/hls_float/hls_float.scala:34:7
  input         clock,	// git/chisel-template/src/main/scala/hls_float/hls_float.scala:34:7
                reset,	// git/chisel-template/src/main/scala/hls_float/hls_float.scala:34:7
  output        i0_ready,	// git/chisel-template/src/main/scala/hls_float/hls_float.scala:35:14
  input         i0_valid,	// git/chisel-template/src/main/scala/hls_float/hls_float.scala:35:14
  input  [31:0] i0_data,	// git/chisel-template/src/main/scala/hls_float/hls_float.scala:35:14
  input         o0_ready,	// git/chisel-template/src/main/scala/hls_float/hls_float.scala:36:14
  output        o0_valid,	// git/chisel-template/src/main/scala/hls_float/hls_float.scala:36:14
  output [31:0] o0_data	// git/chisel-template/src/main/scala/hls_float/hls_float.scala:36:14
);

  reg         valid;	// git/chisel-template/src/main/scala/hls_float/hls_float.scala:37:22
  reg  [31:0] data;	// git/chisel-template/src/main/scala/hls_float/hls_float.scala:38:17
  wire        i0_ready_0 = ~valid | o0_ready;	// git/chisel-template/src/main/scala/hls_float/hls_float.scala:37:22, :39:{15,22}
  always @(posedge clock) begin	// git/chisel-template/src/main/scala/hls_float/hls_float.scala:34:7
    automatic logic _GEN;	// git/chisel-template/src/main/scala/hls_float/hls_float.scala:21:11
    _GEN = i0_ready_0 & i0_valid;	// git/chisel-template/src/main/scala/hls_float/hls_float.scala:21:11, :39:22
    if (reset)	// git/chisel-template/src/main/scala/hls_float/hls_float.scala:34:7
      valid <= 1'h0;	// git/chisel-template/src/main/scala/hls_float/hls_float.scala:34:7, :37:22
    else	// git/chisel-template/src/main/scala/hls_float/hls_float.scala:34:7
      valid <= _GEN | ~(o0_ready & valid) & valid;	// git/chisel-template/src/main/scala/hls_float/hls_float.scala:21:11, :37:22, :42:19, :43:11, :45:19, :46:11
    if (_GEN)	// git/chisel-template/src/main/scala/hls_float/hls_float.scala:21:11
      data <= i0_data;	// git/chisel-template/src/main/scala/hls_float/hls_float.scala:38:17
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// git/chisel-template/src/main/scala/hls_float/hls_float.scala:34:7
    `ifdef FIRRTL_BEFORE_INITIAL	// git/chisel-template/src/main/scala/hls_float/hls_float.scala:34:7
      `FIRRTL_BEFORE_INITIAL	// git/chisel-template/src/main/scala/hls_float/hls_float.scala:34:7
    `endif // FIRRTL_BEFORE_INITIAL
    initial begin	// git/chisel-template/src/main/scala/hls_float/hls_float.scala:34:7
      automatic logic [31:0] _RANDOM[0:1];	// git/chisel-template/src/main/scala/hls_float/hls_float.scala:34:7
      `ifdef INIT_RANDOM_PROLOG_	// git/chisel-template/src/main/scala/hls_float/hls_float.scala:34:7
        `INIT_RANDOM_PROLOG_	// git/chisel-template/src/main/scala/hls_float/hls_float.scala:34:7
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// git/chisel-template/src/main/scala/hls_float/hls_float.scala:34:7
        for (logic [1:0] i = 2'h0; i < 2'h2; i += 2'h1) begin
          _RANDOM[i[0]] = `RANDOM;	// git/chisel-template/src/main/scala/hls_float/hls_float.scala:34:7
        end	// git/chisel-template/src/main/scala/hls_float/hls_float.scala:34:7
        valid = _RANDOM[1'h0][0];	// git/chisel-template/src/main/scala/hls_float/hls_float.scala:34:7, :37:22
        data = {_RANDOM[1'h0][31:1], _RANDOM[1'h1][0]};	// git/chisel-template/src/main/scala/hls_float/hls_float.scala:34:7, :37:22, :38:17
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// git/chisel-template/src/main/scala/hls_float/hls_float.scala:34:7
      `FIRRTL_AFTER_INITIAL	// git/chisel-template/src/main/scala/hls_float/hls_float.scala:34:7
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  assign i0_ready = i0_ready_0;	// git/chisel-template/src/main/scala/hls_float/hls_float.scala:34:7, :39:22
  assign o0_valid = valid;	// git/chisel-template/src/main/scala/hls_float/hls_float.scala:34:7, :37:22
  assign o0_data = data;	// git/chisel-template/src/main/scala/hls_float/hls_float.scala:34:7, :38:17
endmodule

module op_FPOP_mul_I32W_I32W_O32W(	// git/chisel-template/src/main/scala/hls_float/hls_float.scala:230:7
  output        i0_ready,	// git/chisel-template/src/main/scala/hls_float/hls_float.scala:231:14
  input         i0_valid,	// git/chisel-template/src/main/scala/hls_float/hls_float.scala:231:14
  input  [31:0] i0_data,	// git/chisel-template/src/main/scala/hls_float/hls_float.scala:231:14
  output        i1_ready,	// git/chisel-template/src/main/scala/hls_float/hls_float.scala:232:14
  input         i1_valid,	// git/chisel-template/src/main/scala/hls_float/hls_float.scala:232:14
  input  [31:0] i1_data,	// git/chisel-template/src/main/scala/hls_float/hls_float.scala:232:14
  input         o0_ready,	// git/chisel-template/src/main/scala/hls_float/hls_float.scala:233:14
  output        o0_valid,	// git/chisel-template/src/main/scala/hls_float/hls_float.scala:233:14
  output [31:0] o0_data,	// git/chisel-template/src/main/scala/hls_float/hls_float.scala:233:14
  input         clk,	// git/chisel-template/src/main/scala/hls_float/hls_float.scala:234:15
                reset	// git/chisel-template/src/main/scala/hls_float/hls_float.scala:235:17
);

  wire        _delay_i0_ready;	// git/chisel-template/src/main/scala/hls_float/hls_float.scala:240:25
  wire        _vivado_fmul_comb_m_axis_result_tvalid;	// git/chisel-template/src/main/scala/hls_float/hls_float.scala:239:23
  wire [31:0] _vivado_fmul_comb_m_axis_result_tdata;	// git/chisel-template/src/main/scala/hls_float/hls_float.scala:239:23
  wire        i1_ready_0 = _delay_i0_ready & _vivado_fmul_comb_m_axis_result_tvalid;	// git/chisel-template/src/main/scala/hls_float/hls_float.scala:21:11, :239:23, :240:25
  vivado_fmul_comb vivado_fmul_comb (	// git/chisel-template/src/main/scala/hls_float/hls_float.scala:239:23
    .s_axis_a_tvalid      (i0_valid),
    .s_axis_a_tdata       (i0_data),
    .s_axis_b_tvalid      (i1_valid),
    .s_axis_b_tdata       (i1_data),
    .m_axis_result_tvalid (_vivado_fmul_comb_m_axis_result_tvalid),
    .m_axis_result_tdata  (_vivado_fmul_comb_m_axis_result_tdata)
  );	// git/chisel-template/src/main/scala/hls_float/hls_float.scala:239:23
  op_FPOP_mul_I32W_I32W_O32W_HandshakeSingleDelay delay (	// git/chisel-template/src/main/scala/hls_float/hls_float.scala:240:25
    .clock    (clk),
    .reset    (reset),
    .i0_ready (_delay_i0_ready),
    .i0_valid (_vivado_fmul_comb_m_axis_result_tvalid),	// git/chisel-template/src/main/scala/hls_float/hls_float.scala:239:23
    .i0_data  (_vivado_fmul_comb_m_axis_result_tdata),	// git/chisel-template/src/main/scala/hls_float/hls_float.scala:239:23
    .o0_ready (o0_ready),
    .o0_valid (o0_valid),
    .o0_data  (o0_data)
  );	// git/chisel-template/src/main/scala/hls_float/hls_float.scala:240:25
  assign i0_ready = i1_ready_0;	// git/chisel-template/src/main/scala/hls_float/hls_float.scala:21:11, :230:7
  assign i1_ready = i1_ready_0;	// git/chisel-template/src/main/scala/hls_float/hls_float.scala:21:11, :230:7
endmodule


