// Generated by CIRCT firtool-1.109.0
module op_FP_2_0E_0__O32W(	// git/chisel-template/src/main/scala/hls_float/hls_float.scala:281:7
  input         o0_ready,	// git/chisel-template/src/main/scala/hls_float/hls_float.scala:282:14
  output        o0_valid,	// git/chisel-template/src/main/scala/hls_float/hls_float.scala:282:14
  output [31:0] o0_data,	// git/chisel-template/src/main/scala/hls_float/hls_float.scala:282:14
  input         clk,	// git/chisel-template/src/main/scala/hls_float/hls_float.scala:283:15
                reset	// git/chisel-template/src/main/scala/hls_float/hls_float.scala:284:17
);

  assign o0_valid = 1'h1;	// git/chisel-template/src/main/scala/hls_float/hls_float.scala:281:7
  assign o0_data = 32'h40000000;	// git/chisel-template/src/main/scala/hls_float/hls_float.scala:281:7, :287:32
endmodule


